# ░█████╗░███████╗░█████╗░███╗░░██╗██╗░░░██╗██╗██╗░░░░░██████╗░░█████╗░████████╗██╗░█████╗░███╗░░██╗░██████╗
# ██╔══██╗██╔════╝██╔══██╗████╗░██║██║░░░██║██║██║░░░░░██╔══██╗██╔══██╗╚══██╔══╝██║██╔══██╗████╗░██║██╔════╝
# ███████║█████╗░░███████║██╔██╗██║╚██╗░██╔╝██║██║░░░░░██████╔╝██║░░██║░░░██║░░░██║██║░░██║██╔██╗██║╚█████╗░
# ██╔══██║██╔══╝░░██╔══██║██║╚████║░╚████╔╝░██║██║░░░░░██╔═══╝░██║░░██║░░░██║░░░██║██║░░██║██║╚████║░╚═══██╗
# ██║░░██║██║░░░░░██║░░██║██║░╚███║░░╚██╔╝░░██║███████╗██║░░░░░╚█████╔╝░░░██║░░░██║╚█████╔╝██║░╚███║██████╔╝
# ╚═╝░░╚═╝╚═╝░░░░░╚═╝░░╚═╝╚═╝░░╚══╝░░░╚═╝░░░╚═╝╚══════╝╚═╝░░░░░░╚════╝░░░░╚═╝░░░╚═╝░╚════╝░╚═╝░░╚══╝╚═════╝░
# Автор плагина: anton_flame (ТГК: https://t.me/anton_flame_coder)

settings:
  level-2:
    # Включено ли улучшение зелий до 2 уровня
    enabled: true
    # Обязательно ли у игрока должно быть право afanvilpotions.upgrade.level.2 для улучшения зелий
    check-permission: false
    # Настройка зелий, которые можно улучшать (можно добавлять какие угодно)
    potions:
      increase_damage:
        # Длительность зелья в тиках
        duration: 1800
        # Цена в уровнях опыта за улучшение зелья (0 = нисколько)
        exp-price: 7
        # Название улучшенного зелья
        potion-name: "&aУлучшенное зелье силы"
      speed:
        # Длительность зелья в тиках
        duration: 1800
        # Цена в уровнях опыта за улучшение зелья (0 = нисколько)
        exp-price: 5
        # Название улучшенного зелья
        potion-name: "&aУлучшенное зелье скорости"
      heal:
        # Длительность зелья в тиках
        duration: 1
        # Цена в уровнях опыта за улучшение зелья (0 = нисколько)
        exp-price: 4
        # Название улучшенного зелья
        potion-name: "&aУлучшенное зелье исцеления"
      regeneration:
        # Длительность зелья в тиках
        duration: 440
        # Цена в уровнях опыта за улучшение зелья (0 = нисколько)
        exp-price: 3
        # Название улучшенного зелья
        potion-name: "&aУлучшенное зелье регенерации"
      jump:
        # Длительность зелья в тиках
        duration: 1800
        # Цена в уровнях опыта за улучшение зелья (0 = нисколько)
        exp-price: 2
        # Название улучшенного зелья
        potion-name: "&aУлучшенное зелье прыгучести"

  level-3:
    # Включено ли улучшение зелий до 3 уровня
    enabled: true
    # Обязательно ли у игрока должно быть право afanvilpotions.upgrade.level.3 для улучшения зелий
    check-permission: false
    # Настройка зелий, которые можно улучшать (можно добавлять какие угодно)
    potions:
      increase_damage:
        # Длительность зелья в тиках
        duration: 1800
        # Цена в уровнях опыта за улучшение зелья (0 = нисколько)
        exp-price: 15
        # Название улучшенного зелья
        potion-name: "&aУлучшенное зелье силы"
      speed:
        # Длительность зелья в тиках
        duration: 1800
        # Цена в уровнях опыта за улучшение зелья (0 = нисколько)
        exp-price: 10
        # Название улучшенного зелья
        potion-name: "&aУлучшенное зелье скорости"
      heal:
        # Длительность зелья в тиках
        duration: 1
        # Цена в уровнях опыта за улучшение зелья (0 = нисколько)
        exp-price: 8
        # Название улучшенного зелья
        potion-name: "&aУлучшенное зелье исцеления"
      regeneration:
        # Длительность зелья в тиках
        duration: 440
        # Цена в уровнях опыта за улучшение зелья (0 = нисколько)
        exp-price: 7
        # Название улучшенного зелья
        potion-name: "&aУлучшенное зелье регенерации"
      jump:
        # Длительность зелья в тиках
        duration: 1800
        # Цена в уровнях опыта за улучшение зелья (0 = нисколько)
        exp-price: 5
        # Название улучшенного зелья
        potion-name: "&aУлучшенное зелье прыгучести"

# Сообщения плагина
messages:
  # Сообщение при недостатке прав
  no-permission: "&cУ Вас недостаточно прав!"
  # Сообщение при перезагрузке конфигурации
  reloaded: "&fКонфигурация была перезагружена!"
  # Хелп-сообщение
  help:
    - ""
    - "&fПомощь по плагину &6AFAnvilPotions&f:"
    - "&6/afanvilpotions reload &f- перезагрузить конфигурацию"
    - ""